from pygments.token import *
STANDARD_TYPES_SP = {
    Token:                         ['tok'],

    Text:                          ['tok','tx'],
    Whitespace:                    ['tok','tx','w'],
    Escape:                        ['tok','tx','esc'],
    Error:                         ['tok','tx','err'],
    Other:                         ['tok','tx','x'],

    Keyword:                       ['tok','k'],
    Keyword.Constant:              ['tok','k','kc'],
    Keyword.Declaration:           ['tok','k','kd'],
    Keyword.Namespace:             ['tok','k','kn'],
    Keyword.Pseudo:                ['tok','k','kp'],
    Keyword.Reserved:              ['tok','k','kr'],
    Keyword.Type:                  ['tok','k','kt'],

    Name:                          ['tok','n'],
    Name.Attribute:                ['tok','n','na'],
    Name.Builtin:                  ['tok','n','nb'],
    Name.Builtin.Pseudo:           ['tok','n','bp'],
    Name.Class:                    ['tok','n','nc'],
    Name.Constant:                 ['tok','n','no'],
    Name.Decorator:                ['tok','n','nd'],
    Name.Entity:                   ['tok','n','ni'],
    Name.Exception:                ['tok','n','ne'],
    Name.Function:                 ['tok','n','nf'],
    Name.Function.Magic:           ['tok','n','nf','fm'],
    Name.Property:                 ['tok','n','py'],
    Name.Label:                    ['tok','n','nl'],
    Name.Namespace:                ['tok','n','nn'],
    Name.Other:                    ['tok','n','nx'],
    Name.Tag:                      ['tok','n','nt'],
    Name.Variable:                 ['tok','n','nv'],
    Name.Variable.Class:           ['tok','n','nv','vc'],
    Name.Variable.Global:          ['tok','n','nv','vg'],
    Name.Variable.Instance:        ['tok','n','nv','vi'],
    Name.Variable.Magic:           ['tok','n','nv','vm'],

    Literal:                       ['tok','l'],
    Literal.Date:                  ['tok','l','ld'],

    String:                        ['tok','s'],
    String.Affix:                  ['tok','s','sa'],
    String.Backtick:               ['tok','s','sb'],
    String.Char:                   ['tok','s','sc'],
    String.Delimiter:              ['tok','s','dl'],
    String.Doc:                    ['tok','s','sd'],
    String.Double:                 ['tok','s','s2'],
    String.Escape:                 ['tok','s','se'],
    String.Heredoc:                ['tok','s','sh'],
    String.Interpol:               ['tok','s','si'],
    String.Other:                  ['tok','s','sx'],
    String.Regex:                  ['tok','s','sr'],
    String.Single:                 ['tok','s','s1'],
    String.Symbol:                 ['tok','s','ss'],

    Number:                        ['tok','m'],
    Number.Bin:                    ['tok','m','mb'],
    Number.Float:                  ['tok','m','mf'],
    Number.Hex:                    ['tok','m','mh'],
    Number.Integer:                ['tok','m','mi'],
    Number.Integer.Long:           ['tok','m','mi','il'],
    Number.Oct:                    ['tok','m','mo'],

    Operator:                      ['tok','o'],
    Operator.Word:                 ['tok','o','ow'],

    Punctuation:                   ['tok','p'],
    Punctuation.Marker:            ['tok','p','pm'],

    Comment:                       ['tok','c'],
    Comment.Hashbang:              ['tok','c','ch'],
    Comment.Multiline:             ['tok','c','cm'],
    Comment.Preproc:               ['tok','c','cp'],
    Comment.PreprocFile:           ['tok','c','cpf'],
    Comment.Single:                ['tok','c','c1'],
    Comment.Special:               ['tok','c','cs'],

    Generic:                       ['tok','g'],
    Generic.Deleted:               ['tok','g','gd'],
    Generic.Emph:                  ['tok','g','ge'],
    Generic.Error:                 ['tok','g','gr'],
    Generic.Heading:               ['tok','g','gh'],
    Generic.Inserted:              ['tok','g','gi'],
    Generic.Output:                ['tok','g','go'],
    Generic.Prompt:                ['tok','g','gp'],
    Generic.Strong:                ['tok','g','gs'],
    Generic.Subheading:            ['tok','g','gu'],
    Generic.EmphStrong:            ['tok','g','ges'],
    Generic.Traceback:             ['tok','g','gt'],
}